### ISSUE TITLE
Design Project Structure for backend

### ISSUE THREAD

**Issue by africa-playground** [africa-playground/images.africa#3]
Design Project Structure for backend: setup the project structure for the backend,
 create apps, 
folders, 
asset etc
Assigned to Rasheed
Make sure you close this issues after youre done

Helpful link: 
https://github.com/shalam15/djangoMasterApiAndProjectTemplate
https://www.askpython.com/django/django-app-structure-project-structure

**Comment by Yomi04** [comment]
Created a backend structure for the intended project.
